[package]
name = "populate-prefixes"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
config = { path = "../config" }
itertools = "0.14.0"
serde_yaml = "0.9.34"
